### PR TITLE
Improve overwriting files

### LINKED ISSUE #5: BUG: Files can be duplicated if deleted files exist
If a file small enough to fit into a deleted chunk of free space is written with `overwrite==true`, it will be inserted into that space but the previous version that exists later on in the filesystem will not be overwritten. See

https://github.com/charlesbaynham/OSFS/blob/5002c74fc9a09a3a3b932bef34c5daba36868860/src/OSFS.cpp#L130-L135

### PR DESCRIPTION
**Pull request by charlesbaynham**
Changes from @dHutchings in PR #4:

> Previously, if you tried to write a new file, while overwriting a
> previous one, it would return the FILE_ALREADY_EXISTS error if the
> filesizes weren't the same.
> 
> This doesn't make sense, espescially since the user explititly set the
> overwrite flag true.
> 
> This new behaviour returns FILE_ALREADY_EXISTS only if overwrite is
> false.
> 
> If overwrite is true and it encounters an identically named file, it
> either uses it (if the sizes are identical) or deletes it and moves on.

(cherry picked from commit f62b6cb050f94f5e71fc10d63834acd2827a75f0)

### CODE REVIEW

**Comment by charlesbaynham** [comment]
In general, the way OSFS handles overwriting is a bit shaky at the moment. For example, we can end up with duplicate files on the filesystem (#5) and there's duplication of logic. 

I think a bit of a refactor is in order. How about:

* [x] If `overwrite == false`, `newFile` should use `getFileInfo` to ensure that the file does not exist before writing it. 
* [x] If `overwrite == true`, `newFile` should use `deleteFile` to ensure that the file does not exist before writing it. 
* [x] Since the result of these checks will mean that `newFile` should have the same conditions for `overwrite == true or false`, we can remove all overwriting-related logic from the search loop: the normal check for fitting into a deleted file will work whether that file used to have the same name or not

**Comment by charlesbaynham** [comment]
@dHutchings I've done the refactor I mentioned above: this code should now support adding larger / smaller files and it shouldn't create duplicates on the filesystem under any circumstances. 

I haven't got access to a microcontroller (stuck at home...), would you mind trying these changes out and seeing if they work for your case?

**Comment by dHutchings** [comment]
@charlesbaynham tested changes (not that rigorously).  Seems to work.

Platform was a teensy 3.2 microcontroller.

Thank you! This library is great.

**Comment by charlesbaynham** [comment]
Brilliant! Glad you like it

**Pull request merged**
